#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json
from pathlib import Path

def md_cell(text):
    return {"cell_type": "markdown", "id": f"md{abs(hash(text[:20]))%99999:05d}",
            "metadata": {}, "source": text}

def code_cell(text):
    return {"cell_type": "code", "execution_count": None,
            "id": f"cc{abs(hash(text[:20]))%99999:05d}",
            "metadata": {}, "outputs": [], "source": text}

cells = []

cells.append(md_cell(
    "# Milestone 2 \u2013 Klasteryzacja sygna\u0142\u00f3w z sensor\u00f3w\n\n"
    "**Aktywno\u015bci = Ground Truth.** Cel: zbada\u0107, czy na podstawie samych sygna\u0142\u00f3w\n"
    "sensorycznych mo\u017cna odtworzy\u0107 podzia\u0142 na aktywno\u015bci \u2013 i kt\u00f3ra metoda klasteryzacji\n"
    "robi to najlepiej.\n\n"
    "Pipeline: NaN/outliery \u2192 normalizacja \u2192 (PCA) \u2192 klasteryzacja (K-Means, DBSCAN, HDBSCAN)\n"
    "\u2192 por\u00f3wnanie z GT \u2192 wyb\u00f3r najlepszej metody \u2192 macierz przej\u015b\u0107\n"
))

cells.append(code_cell(
    "from pathlib import Path\n"
    "import json\n"
    "import pandas as pd\n"
    "import numpy as np\n"
    "import matplotlib.pyplot as plt\n"
    "import warnings\n"
    "warnings.filterwarnings('ignore')\n"
    "pd.set_option('display.max_columns', 60)\n"
    "SEED = 42\n"
    "np.random.seed(SEED)\n"
    "\n"
    "# Wczytanie danych\n"
    "candidate_dirs = [Path('.'), Path('Dataset_8087219'), Path('..') / 'Dataset_8087219']\n"
    "DATA_DIR = None\n"
    "for d in candidate_dirs:\n"
    "    if (d / 'Signature_Burn.txt').exists():\n"
    "        DATA_DIR = d.resolve()\n"
    "        break\n"
    "if DATA_DIR is None:\n"
    "    raise FileNotFoundError('Nie znaleziono folderu z plikami Signature_*.txt.')\n"
    "\n"
    "signature_files = sorted(DATA_DIR.glob('Signature_*.txt'))\n"
    "records = []\n"
    "for fp in signature_files:\n"
    "    activity = fp.stem.replace('Signature_', '')\n"
    "    with fp.open('r', encoding='utf-8') as f:\n"
    "        for idx, line in enumerate(f, 1):\n"
    "            line = line.strip()\n"
    "            if not line: continue\n"
    "            obj = json.loads(line)\n"
    "            row = {'activity': activity, 'event_index': idx,\n"
    "                   'station': obj.get('station'), 'timestamp_raw': obj.get('timestamp')}\n"
    "            for k, v in obj.get('events', {}).items():\n"
    "                row[k] = v\n"
    "            records.append(row)\n"
    "\n"
    "df = pd.DataFrame(records)\n"
    "df['timestamp'] = pd.to_datetime(df['timestamp_raw'], utc=True, errors='coerce')\n"
    "META = ['activity','event_index','station','timestamp_raw','timestamp']\n"
    "SIG_COLS = [c for c in df.columns if c not in META]\n"
    "activities = sorted(df['activity'].unique())\n"
    "y_true = df['activity'].values  # Ground Truth\n"
    "\n"
    "print(f'Eventow: {len(df)}, Sygnalow: {len(SIG_COLS)}, Aktywnosci (GT): {len(activities)}')\n"
    "print(f'Aktywnosci: {activities}')\n"
))

cells.append(md_cell(
    "## 1. Analiza NaN i outlier\u00f3w w sygna\u0142ach\n"
))

cells.append(code_cell(
    "# Analiza NaN\n"
    "nan_per_col = df[SIG_COLS].isna().sum()\n"
    "print('=== BRAKUJACE WARTOSCI (NaN) PER SYGNAL ===')\n"
    "for col in SIG_COLS:\n"
    "    n = nan_per_col[col]\n"
    "    active_for = ', '.join(df[df[col].notna()]['activity'].unique())\n"
    "    print(f'  {col:22s}: {n:3d} NaN ({n/len(df)*100:4.0f}%) | aktywny dla: {active_for}')\n"
    "\n"
    "print(f'\\nStrategia: NaN -> 0 (sygnal nieaktywny = komponent nie pracuje)')\n"
    "\n"
    "# Outliery w wartosciach sygnalow\n"
    "all_vals = df[SIG_COLS].stack().dropna().unique()\n"
    "print(f'\\nWartosci unikalne PRZED normalizacja: {sorted(all_vals)}')\n"
    "print('Brak outlierow numerycznych - dane dyskretne {-512, 0, 1, 512}')\n"
    "\n"
    "# Outliery czasowe\n"
    "df_s = df.sort_values(['activity','event_index']).copy()\n"
    "df_s['dt'] = df_s.groupby('activity')['timestamp'].diff().dt.total_seconds()\n"
    "outliers_t = df_s[df_s['dt'].notna() & ((df_s['dt'] > 3) | (df_s['dt'] < 1))]\n"
    "print(f'\\nOutliery czasowe (odstep >3s lub <1s): {len(outliers_t)} z {df_s[\"dt\"].notna().sum()}')\n"
    "print('Interpretacja: artefakty rejestracji PLC, nie bledy procesu.')\n"
))

cells.append(md_cell(
    "## 2. Normalizacja sygna\u0142\u00f3w\n"
))

cells.append(code_cell(
    "# Normalizacja: 512->1, -512->-1, NaN->0\n"
    "df_norm = df.copy()\n"
    "for col in SIG_COLS:\n"
    "    df_norm[col] = df_norm[col].apply(lambda x: x/512 if pd.notna(x) and abs(x)>1 else x)\n"
    "df_norm[SIG_COLS] = df_norm[SIG_COLS].fillna(0)\n"
    "\n"
    "X = df_norm[SIG_COLS].values.astype(float)\n"
    "print(f'Macierz cech: {X.shape}')\n"
    "print(f'Wartosci unikalne PO normalizacji: {sorted(np.unique(X))}')\n"
    "\n"
    "# Dodatkowe warianty normalizacji dla klasteryzacji\n"
    "from sklearn.preprocessing import MinMaxScaler, StandardScaler\n"
    "from sklearn.decomposition import PCA\n"
    "\n"
    "X_mm = MinMaxScaler().fit_transform(X)  # [0,1]\n"
    "X_std = StandardScaler().fit_transform(X)  # z-score\n"
    "\n"
    "# PCA\n"
    "pca5 = PCA(n_components=5, random_state=SEED)\n"
    "X_pca5 = pca5.fit_transform(X_mm)\n"
    "pca2 = PCA(n_components=2, random_state=SEED)\n"
    "X_pca2 = pca2.fit_transform(X_mm)\n"
    "\n"
    "print(f'PCA 5 komponentow - wariancja: {pca5.explained_variance_ratio_.sum()*100:.1f}%')\n"
    "print(f'PCA 2 komponenty  - wariancja: {pca2.explained_variance_ratio_.sum()*100:.1f}%')\n"
    "\n"
    "# Wizualizacja PCA 2D\n"
    "fig, ax = plt.subplots(figsize=(10, 7))\n"
    "colors_act = plt.cm.Set1.colors\n"
    "cmap = {a: colors_act[i] for i, a in enumerate(activities)}\n"
    "for act in activities:\n"
    "    mask = df['activity'] == act\n"
    "    ax.scatter(X_pca2[mask, 0], X_pca2[mask, 1], c=[cmap[act]], label=act,\n"
    "              s=60, alpha=0.85, edgecolors='white', linewidths=0.5)\n"
    "ax.set_xlabel(f'PC1 ({pca2.explained_variance_ratio_[0]*100:.1f}%)', fontsize=11)\n"
    "ax.set_ylabel(f'PC2 ({pca2.explained_variance_ratio_[1]*100:.1f}%)', fontsize=11)\n"
    "ax.set_title('PCA 2D - aktywnosci (Ground Truth)', fontweight='bold')\n"
    "ax.legend(fontsize=10)\n"
    "plt.tight_layout()\n"
    "plt.savefig('m2_pca2d_gt.png', dpi=120, bbox_inches='tight')\n"
    "plt.show()\n"
))

cells.append(md_cell(
    "## 3. Klasteryzacja \u2013 K-Means\n"
))

cells.append(code_cell(
    "from sklearn.cluster import KMeans\n"
    "from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score, silhouette_score\n"
    "\n"
    "# Grid search K-Means\n"
    "km_results = []\n"
    "datasets = {'Raw_26D': X_mm, 'PCA_5': X_pca5, 'PCA_2': X_pca2}\n"
    "\n"
    "for dname, Xd in datasets.items():\n"
    "    for k in range(2, 10):\n"
    "        km = KMeans(n_clusters=k, random_state=SEED, n_init=20)\n"
    "        labels = km.fit_predict(Xd)\n"
    "        ari = adjusted_rand_score(y_true, labels)\n"
    "        nmi = normalized_mutual_info_score(y_true, labels)\n"
    "        sil = silhouette_score(Xd, labels) if len(set(labels)) > 1 else -1\n"
    "        km_results.append({'Dane': dname, 'k': k, 'ARI': round(ari, 3),\n"
    "                           'NMI': round(nmi, 3), 'Silhouette': round(sil, 3)})\n"
    "\n"
    "km_df = pd.DataFrame(km_results)\n"
    "print('=== K-MEANS: GRID SEARCH ===')\n"
    "print(km_df.to_string(index=False))\n"
    "\n"
    "# Najlepszy wynik\n"
    "best_km = km_df.loc[km_df['ARI'].idxmax()]\n"
    "print(f'\\nNajlepszy K-Means: {best_km[\"Dane\"]}, k={best_km[\"k\"]}, '\n"
    "      f'ARI={best_km[\"ARI\"]}, NMI={best_km[\"NMI\"]}, Sil={best_km[\"Silhouette\"]}')\n"
))

cells.append(code_cell(
    "# Wizualizacja K-Means k=6 vs GT\n"
    "best_data_name = best_km['Dane']\n"
    "best_X = datasets[best_data_name]\n"
    "km_best = KMeans(n_clusters=int(best_km['k']), random_state=SEED, n_init=20)\n"
    "km_labels = km_best.fit_predict(best_X)\n"
    "\n"
    "# Macierz konfuzji\n"
    "print('=== MACIERZ KONFUZJI: K-Means vs Ground Truth ===')\n"
    "ct = pd.crosstab(df['activity'], km_labels, rownames=['Aktywnosc (GT)'], colnames=['Klaster'])\n"
    "print(ct.to_string())\n"
    "\n"
    "# Wizualizacja na PCA 2D\n"
    "fig, axes = plt.subplots(1, 2, figsize=(14, 6))\n"
    "cluster_colors = plt.cm.tab10.colors\n"
    "for c in range(int(best_km['k'])):\n"
    "    mask = km_labels == c\n"
    "    axes[0].scatter(X_pca2[mask, 0], X_pca2[mask, 1], c=[cluster_colors[c]],\n"
    "                    label=f'Klaster {c}', s=60, alpha=0.85, edgecolors='white')\n"
    "axes[0].set_title(f'K-Means k={int(best_km[\"k\"])} ({best_data_name})\\n'\n"
    "                  f'ARI={best_km[\"ARI\"]}, NMI={best_km[\"NMI\"]}', fontweight='bold')\n"
    "axes[0].legend(fontsize=8)\n"
    "axes[0].set_xlabel('PC1'); axes[0].set_ylabel('PC2')\n"
    "\n"
    "for act in activities:\n"
    "    mask = df['activity'] == act\n"
    "    axes[1].scatter(X_pca2[mask, 0], X_pca2[mask, 1], c=[cmap[act]],\n"
    "                    label=act, s=60, alpha=0.85, edgecolors='white')\n"
    "axes[1].set_title('Ground Truth (aktywnosci)', fontweight='bold')\n"
    "axes[1].legend(fontsize=8)\n"
    "axes[1].set_xlabel('PC1'); axes[1].set_ylabel('PC2')\n"
    "plt.tight_layout()\n"
    "plt.savefig('m2_kmeans_vs_gt.png', dpi=120, bbox_inches='tight')\n"
    "plt.show()\n"
))

cells.append(md_cell(
    "## 4. Klasteryzacja \u2013 DBSCAN\n"
))

cells.append(code_cell(
    "from sklearn.cluster import DBSCAN\n"
    "\n"
    "# Grid search DBSCAN\n"
    "db_results = []\n"
    "for eps in [0.3, 0.5, 0.7, 1.0, 1.5, 2.0, 2.5, 3.0]:\n"
    "    for ms in [2, 3, 5]:\n"
    "        db = DBSCAN(eps=eps, min_samples=ms)\n"
    "        labels = db.fit_predict(X_pca5)\n"
    "        n_clusters = len(set(labels)) - (1 if -1 in labels else 0)\n"
    "        n_noise = (labels == -1).sum()\n"
    "        noise_pct = n_noise / len(labels) * 100\n"
    "        if n_clusters >= 2:\n"
    "            mask_valid = labels != -1\n"
    "            ari = adjusted_rand_score(y_true[mask_valid], labels[mask_valid]) if mask_valid.sum() > 1 else -1\n"
    "            nmi = normalized_mutual_info_score(y_true[mask_valid], labels[mask_valid]) if mask_valid.sum() > 1 else -1\n"
    "            sil = silhouette_score(X_pca5[mask_valid], labels[mask_valid]) if mask_valid.sum() > 1 and len(set(labels[mask_valid])) > 1 else -1\n"
    "        else:\n"
    "            ari, nmi, sil = -1, -1, -1\n"
    "        db_results.append({'eps': eps, 'min_samples': ms, 'Klastry': n_clusters,\n"
    "                           'Szum_%': round(noise_pct, 1), 'ARI': round(ari, 3),\n"
    "                           'NMI': round(nmi, 3), 'Silhouette': round(sil, 3)})\n"
    "\n"
    "db_df = pd.DataFrame(db_results)\n"
    "print('=== DBSCAN: GRID SEARCH (dane: PCA-5, StandardScaler) ===')\n"
    "print(db_df[db_df['Klastry'] >= 2].to_string(index=False))\n"
    "\n"
    "valid_db = db_df[db_df['ARI'] > 0]\n"
    "if len(valid_db) > 0:\n"
    "    best_db = valid_db.loc[valid_db['ARI'].idxmax()]\n"
    "    print(f'\\nNajlepszy DBSCAN: eps={best_db[\"eps\"]}, min_samples={best_db[\"min_samples\"]}, '\n"
    "          f'Klastry={best_db[\"Klastry\"]}, ARI={best_db[\"ARI\"]}, Szum={best_db[\"Szum_%\"]}%')\n"
    "else:\n"
    "    print('\\nDBSCAN nie znalazl sensownych klastrow dla tych parametrow.')\n"
    "    best_db = db_df.iloc[0]  # placeholder\n"
))

cells.append(md_cell(
    "## 5. Klasteryzacja \u2013 HDBSCAN\n"
))

cells.append(code_cell(
    "import hdbscan\n"
    "\n"
    "# Grid search HDBSCAN\n"
    "hdb_results = []\n"
    "for mcs in [3, 5, 7, 10, 15]:\n"
    "    for ms in [2, 3, 5]:\n"
    "        hdb = hdbscan.HDBSCAN(min_cluster_size=mcs, min_samples=ms)\n"
    "        labels = hdb.fit_predict(X_pca5)\n"
    "        n_clusters = len(set(labels)) - (1 if -1 in labels else 0)\n"
    "        n_noise = (labels == -1).sum()\n"
    "        noise_pct = n_noise / len(labels) * 100\n"
    "        if n_clusters >= 2:\n"
    "            mask_valid = labels != -1\n"
    "            ari = adjusted_rand_score(y_true[mask_valid], labels[mask_valid]) if mask_valid.sum() > 1 else -1\n"
    "            nmi = normalized_mutual_info_score(y_true[mask_valid], labels[mask_valid]) if mask_valid.sum() > 1 else -1\n"
    "            sil = silhouette_score(X_pca5[mask_valid], labels[mask_valid]) if mask_valid.sum() > 1 and len(set(labels[mask_valid])) > 1 else -1\n"
    "        else:\n"
    "            ari, nmi, sil = -1, -1, -1\n"
    "        hdb_results.append({'min_cluster_size': mcs, 'min_samples': ms,\n"
    "                            'Klastry': n_clusters, 'Szum_%': round(noise_pct, 1),\n"
    "                            'ARI': round(ari, 3), 'NMI': round(nmi, 3),\n"
    "                            'Silhouette': round(sil, 3)})\n"
    "\n"
    "hdb_df = pd.DataFrame(hdb_results)\n"
    "print('=== HDBSCAN: GRID SEARCH (dane: PCA-5) ===')\n"
    "print(hdb_df[hdb_df['Klastry'] >= 2].to_string(index=False))\n"
    "\n"
    "valid_hdb = hdb_df[hdb_df['ARI'] > 0]\n"
    "if len(valid_hdb) > 0:\n"
    "    best_hdb = valid_hdb.loc[valid_hdb['ARI'].idxmax()]\n"
    "    print(f'\\nNajlepszy HDBSCAN: mcs={best_hdb[\"min_cluster_size\"]}, ms={best_hdb[\"min_samples\"]}, '\n"
    "          f'Klastry={best_hdb[\"Klastry\"]}, ARI={best_hdb[\"ARI\"]}, Szum={best_hdb[\"Szum_%\"]}%')\n"
    "else:\n"
    "    print('\\nHDBSCAN nie znalazl sensownych klastrow.')\n"
    "    best_hdb = hdb_df.iloc[0]\n"
))

cells.append(md_cell(
    "## 6. Por\u00f3wnanie klastr\u00f3w z aktywno\u015bciami (Ground Truth)\n"
))

cells.append(code_cell(
    "# Porownanie zbiorcze\n"
    "print('=' * 70)\n"
    "print('POROWNANIE ZBIORCZE ALGORYTMOW KLASTERYZACJI')\n"
    "print('=' * 70)\n"
    "\n"
    "comparison = []\n"
    "comparison.append({'Algorytm': 'K-Means', 'Parametry': f'k={int(best_km[\"k\"])}, dane={best_km[\"Dane\"]}',\n"
    "                   'ARI': best_km['ARI'], 'NMI': best_km['NMI'],\n"
    "                   'Silhouette': best_km['Silhouette'], 'Klastry': int(best_km['k']), 'Szum_%': 0})\n"
    "\n"
    "if len(valid_db) > 0:\n"
    "    comparison.append({'Algorytm': 'DBSCAN',\n"
    "                       'Parametry': f'eps={best_db[\"eps\"]}, ms={best_db[\"min_samples\"]}',\n"
    "                       'ARI': best_db['ARI'], 'NMI': best_db['NMI'],\n"
    "                       'Silhouette': best_db['Silhouette'],\n"
    "                       'Klastry': int(best_db['Klastry']), 'Szum_%': best_db['Szum_%']})\n"
    "\n"
    "if len(valid_hdb) > 0:\n"
    "    comparison.append({'Algorytm': 'HDBSCAN',\n"
    "                       'Parametry': f'mcs={int(best_hdb[\"min_cluster_size\"])}, ms={int(best_hdb[\"min_samples\"])}',\n"
    "                       'ARI': best_hdb['ARI'], 'NMI': best_hdb['NMI'],\n"
    "                       'Silhouette': best_hdb['Silhouette'],\n"
    "                       'Klastry': int(best_hdb['Klastry']), 'Szum_%': best_hdb['Szum_%']})\n"
    "\n"
    "comp_df = pd.DataFrame(comparison)\n"
    "print(comp_df.to_string(index=False))\n"
    "\n"
    "# Wybor najlepszego\n"
    "best_overall = comp_df.loc[comp_df['ARI'].idxmax()]\n"
    "print(f'\\n>>> NAJLEPSZA METODA: {best_overall[\"Algorytm\"]} ({best_overall[\"Parametry\"]})')\n"
    "print(f'    ARI={best_overall[\"ARI\"]}, NMI={best_overall[\"NMI\"]}, Silhouette={best_overall[\"Silhouette\"]}')\n"
))

cells.append(code_cell(
    "# Macierz konfuzji dla kazdego algorytmu\n"
    "print('=== MACIERZE KONFUZJI: KLASTRY vs AKTYWNOSCI (GT) ===\\n')\n"
    "\n"
    "# K-Means (najlepszy)\n"
    "print(f'--- K-Means (k={int(best_km[\"k\"])}, {best_km[\"Dane\"]}) ---')\n"
    "km_final = KMeans(n_clusters=int(best_km['k']), random_state=SEED, n_init=20)\n"
    "km_final_labels = km_final.fit_predict(datasets[best_km['Dane']])\n"
    "ct_km = pd.crosstab(df['activity'], km_final_labels, rownames=['Aktywnosc'], colnames=['Klaster'])\n"
    "print(ct_km.to_string())\n"
    "print()\n"
    "\n"
    "# DBSCAN (najlepszy)\n"
    "if len(valid_db) > 0:\n"
    "    print(f'--- DBSCAN (eps={best_db[\"eps\"]}, min_samples={best_db[\"min_samples\"]}) ---')\n"
    "    db_final = DBSCAN(eps=float(best_db['eps']), min_samples=int(best_db['min_samples']))\n"
    "    db_final_labels = db_final.fit_predict(X_pca5)\n"
    "    ct_db = pd.crosstab(df['activity'], db_final_labels, rownames=['Aktywnosc'], colnames=['Klaster'])\n"
    "    print(ct_db.to_string())\n"
    "    print(f'  Szum (klaster -1): {(db_final_labels == -1).sum()} eventow')\n"
    "    print()\n"
    "\n"
    "# HDBSCAN (najlepszy)\n"
    "if len(valid_hdb) > 0:\n"
    "    print(f'--- HDBSCAN (mcs={int(best_hdb[\"min_cluster_size\"])}, ms={int(best_hdb[\"min_samples\"])}) ---')\n"
    "    hdb_final = hdbscan.HDBSCAN(min_cluster_size=int(best_hdb['min_cluster_size']),\n"
    "                                 min_samples=int(best_hdb['min_samples']))\n"
    "    hdb_final_labels = hdb_final.fit_predict(X_pca5)\n"
    "    ct_hdb = pd.crosstab(df['activity'], hdb_final_labels, rownames=['Aktywnosc'], colnames=['Klaster'])\n"
    "    print(ct_hdb.to_string())\n"
    "    print(f'  Szum (klaster -1): {(hdb_final_labels == -1).sum()} eventow')\n"
))

cells.append(md_cell(
    "## 7. Macierz przej\u015b\u0107 mi\u0119dzy klastrami\n\n"
    "Dla najlepszej metody klasteryzacji obliczamy macierz przej\u015b\u0107:\n"
    "ile razy event z klastra A jest bezpo\u015brednio nast\u0119powany przez event z klastra B\n"
    "(w porz\u0105dku chronologicznym wewn\u0105trz ka\u017cdej aktywno\u015bci).\n"
))

cells.append(code_cell(
    "# Macierz przejsc dla najlepszej metody\n"
    "# Uzywamy K-Means (najczesciej najlepszy ARI)\n"
    "best_labels = km_final_labels\n"
    "best_algo_name = f'K-Means k={int(best_km[\"k\"])}'\n"
    "\n"
    "n_clusters_best = int(best_km['k'])\n"
    "T = np.zeros((n_clusters_best, n_clusters_best), dtype=int)\n"
    "\n"
    "# Przejscia wewnatrz kazdej aktywnosci (chronologicznie)\n"
    "for act in activities:\n"
    "    mask = df['activity'] == act\n"
    "    act_labels = best_labels[mask]\n"
    "    for i in range(len(act_labels) - 1):\n"
    "        T[act_labels[i], act_labels[i+1]] += 1\n"
    "\n"
    "print(f'=== MACIERZ PRZEJSC MIEDZY KLASTRAMI ({best_algo_name}) ===')\n"
    "T_df = pd.DataFrame(T, index=[f'Klaster {i}' for i in range(n_clusters_best)],\n"
    "                       columns=[f'Klaster {i}' for i in range(n_clusters_best)])\n"
    "print(T_df.to_string())\n"
    "\n"
    "# Wizualizacja macierzy przejsc\n"
    "fig, ax = plt.subplots(figsize=(8, 6))\n"
    "im = ax.imshow(T, cmap='Blues', aspect='auto')\n"
    "plt.colorbar(im, ax=ax, shrink=0.8, label='Liczba przejsc')\n"
    "ax.set_xticks(range(n_clusters_best))\n"
    "ax.set_yticks(range(n_clusters_best))\n"
    "ax.set_xticklabels([f'K{i}' for i in range(n_clusters_best)], fontsize=10)\n"
    "ax.set_yticklabels([f'K{i}' for i in range(n_clusters_best)], fontsize=10)\n"
    "ax.set_xlabel('Klaster docelowy')\n"
    "ax.set_ylabel('Klaster zrodlowy')\n"
    "ax.set_title(f'Macierz przejsc miedzy klastrami\\n({best_algo_name})', fontweight='bold')\n"
    "for i in range(n_clusters_best):\n"
    "    for j in range(n_clusters_best):\n"
    "        if T[i, j] > 0:\n"
    "            ax.text(j, i, str(T[i, j]), ha='center', va='center', fontsize=10,\n"
    "                    color='white' if T[i, j] > T.max()*0.5 else 'black', fontweight='bold')\n"
    "plt.tight_layout()\n"
    "plt.savefig('m2_transition_matrix.png', dpi=120, bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Wykres zapisany: m2_transition_matrix.png')\n"
    "\n"
    "# Interpretacja\n"
    "print('\\n=== INTERPRETACJA MACIERZY PRZEJSC ===')\n"
    "print('Przejscia na diagonali = eventy pozostajace w tym samym klastrze (fazy stabilne)')\n"
    "print('Przejscia poza diagonala = zmiany klastra (przejscia miedzy fazami)')\n"
    "diag_sum = np.trace(T)\n"
    "total = T.sum()\n"
    "print(f'\\nPrzejscia na diagonali: {diag_sum}/{total} ({diag_sum/total*100:.1f}%)')\n"
    "print(f'Przejscia miedzy klastrami: {total-diag_sum}/{total} ({(total-diag_sum)/total*100:.1f}%)')\n"
    "\n"
    "# Ktore aktywnosci sa w ktorych klastrach\n"
    "print('\\n=== MAPOWANIE KLASTROW NA AKTYWNOSCI ===')\n"
    "for c in range(n_clusters_best):\n"
    "    mask = best_labels == c\n"
    "    acts_in_cluster = df['activity'][mask].value_counts()\n"
    "    dominant = acts_in_cluster.index[0]\n"
    "    purity = acts_in_cluster.iloc[0] / acts_in_cluster.sum() * 100\n"
    "    print(f'  Klaster {c}: {dict(acts_in_cluster)} -> dominujaca: {dominant} ({purity:.0f}%)')\n"
))

cells.append(md_cell(
    "## 8. Podsumowanie\n\n"
    "### Pipeline:\n"
    "1. Sygna\u0142y z czujnik\u00f3w (119 event\u00f3w \u00d7 26 sygna\u0142\u00f3w)\n"
    "2. NaN \u2192 0, normalizacja 512\u21921\n"
    "3. Analiza outlier\u00f3w (brak krytycznych)\n"
    "4. PCA (5 komponent\u00f3w, ~90% wariancji)\n"
    "5. Klasteryzacja: K-Means, DBSCAN, HDBSCAN (grid search)\n"
    "6. Por\u00f3wnanie z Ground Truth: ARI, NMI, macierz konfuzji\n"
    "7. Wyb\u00f3r najlepszej metody \u2192 macierz przej\u015b\u0107 mi\u0119dzy klastrami\n"
))

# ─── WRITE NOTEBOOK ──────────────────────────────────────────────────────────
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"}
    },
    "cells": cells
}

out = Path(__file__).parent / 'Milestone2_EDA.ipynb'
with open(out, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f'Zapisano: {out}')
print(f'Liczba komorek: {len(cells)}')
